FROM python:3.11-slim
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    build-essential \
    curl \
    wget \
    gnupg \
    librdkafka-dev \
    && apt-get clean
RUN pip install --no-cache-dir \
    confluent-kafka \
    opensearch \
    fastapi \
    uvicorn \
    pydantic \
    requests \
    psycopg2-binary 
    
WORKDIR /app
COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]
